defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: password

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  min_messages: warning

development:
  <<: *defaults
  database: travis_development

jasmine:
  <<: *defaults
  database: travis_jasmine

production:
  <<: *defaults
  database: travis_production

test:
  <<: *defaults
  database: travis_test

vagrant:
  <<: *defaults
  database: travis_vagrant
