# TODO needs to be updated!
#
oauth2: &oauth2
  authorization_server: https://github.com
  scope: user
  authorize_path: login/oauth/authorize
  access_token_path: login/oauth/access_token
  user_attributes_path: api/v2/json/user/show
  user_attribute_uid_key: user/login

production:
  oauth2:
    client_id: YOUR_GITHUB_CLIENT_ID
    client_secret: YOUR_GITHUB_CLIENT_SECRET
    <<: *oauth2
  hoptoad:
    key: YOUR_HOPTOAD_KEY

development:
  oauth2:
    client_id: YOUR_GITHUB_CLIENT_ID
    client_secret: YOUR_GITHUB_CLIENT_SECRET

test:
  host: test.travis-ci.org

vagrant:
  host: travis-vagrant.musicglue.co
  amqp:
    host: vm-travis-hub
    port: 5672
    username: travisci_hub
    password: travisci_hub_password
    vhost: travisci.vagrantm
  assets:
    host: travis-assets-vagrant.musicglue.com
    version: d91ea46e

